spring.application.name=start

application.recommendations-db.url=jdbc:h2:file:./transaction;DB_CLOSE_ON_EXIT=FALSE
application.recommendations-db.read-only=true

spring.datasource.url=jdbc:postgresql://localhost:5432/myDb
spring.datasource.username=myUser
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

spring.telegram.bot.token=8293448595:AAGnPLmfrDEZQSJjuH4L6ct-XlZ1N_vGZJg
spring.telegram.bot.name=@StarRecommendation_bot
logging.level.org.telegram=DEBUG
logging.level.com.example.start=DEBUG

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.open-in-view=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration