spring.application.name=start
application.recommendations-db.url=jdbc:h2:file:./transaction
spring.datasource.username=myUser
spring.datasource.password=123
spring.datasource.read-only=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration